source 'https://rubygems.org'

gem 'rails-backbone'
gem 'underscore-rails'
gem 'ejs'

gem 'bootstrap-sass'

#default gems

gem 'rails', '4.0.0.rc2'
gem 'sqlite3'

gem 'sass-rails', '~> 4.0.0.rc2'
gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'

gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

